-- Find the first 10 records from the table.
SELECT * FROM sales_data_cleaned limit 10

-- Count the total number of orders.
SELECT count(*) as total_order FROM sales_data_cleaned

-- Find all orders from Mumbai where revenue is greater than 10,000.
SELECT order_id, city, product, revenue
FROM sales_data_cleaned
WHERE city = 'Mumbai' AND revenue > 10000;

-- Find all unique payment methods used.
SELECT DISTINCT(payment_method) from sales_data_cleaned


-- Show top 10 orders with the highest revenue.
SELECT order_id,product,revenue from sales_data_cleaned ORDER BY revenue DESC limit 10

-- Find the minimum, maximum, average, and total revenue across all orders.
SELECT 
    MIN(revenue)  AS min_revenue,
    MAX(revenue)  AS max_revenue,
    round(AVG(revenue))  AS avg_revenue,
    round(SUM(revenue))  AS total_revenue
FROM sales_data_cleaned;

-- Find total revenue generated by each city, highest first.
select city, round(sum(revenue)) as total_revenue from sales_data_cleaned GROUP BY city ORDER BY total_revenue desc limit 1

-- Find products where average rating is below 3.
SELECT product,avg(rating) as average_rates from sales_data_cleaned group by product having avg(rating) < 3 ORDER BY avg(rating) 

-- Calculate return rate percentage for each city.
SELECT city,sum(case when returned = TRUE then 1 else 0 END) as returned_order,
ROUND(100.0 * SUM(CASE WHEN returned = TRUE THEN 1 ELSE 0 END) / COUNT(*), 2) AS return_rate_pct
from sales_data_cleaned
group by city

-- Find products whose average revenue is higher than the overall average revenue.
SELECT product,round(avg(revenue)) as avg_revnue
FROM sales_data_cleaned
GROUP BY product
HAVING avg(revenue)>(SELECT avg(revenue)FROM sales_data_cleaned)
ORDER BY avg(revenue) DESC

-- Rank all cities by total revenue.
SELECT city,sum(revenue)as total_revenue,dense_rank()OVER(ORDER BY sum(revenue) DESC) as ranking 
FROM sales_data_cleaned 
GROUP BY city

